=== Lavie-Inzynierka/klinikaWeterynaryjna/static/json/addpresc.schema.json
{
    "$id": "http://example.com/example.json",
    "$schema": "http://json-schema.org/draft-07/schema",
    "default": {},
    "description": "The root schema comprises the entire JSON document.",
    "required": [
        "code",
        "expiration_date",
        "pet",
        "cures"
    ],
    "title": "The root schema",
    "type": "object",
    "properties": {
        "code": {
            "$id": "#/properties/code",
            "type": "string",
            "title": "The code schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "pattern": "^[0-9]{22}$",
            "examples": [
                "1234567890098765432154"
            ]
        },
        "expiration_date": {
            "$id": "#/properties/expiration_date",
            "type": "string",
            "pattern": "^[1-9][0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$",
            "title": "The expiration_date schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "2019-08-20"
            ]
        },
        "pet": {
            "$id": "#/properties/petid",
            "type": "integer",
            "title": "The petid schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0
        },
        "newPet": {
            "$id": "#/properties/newPet",
            "default": {},
            "description": "An explanation about the purpose of this instance.",

            "required": [
                "name",
                "date_of_birth",
                "sex",
                "species",
                "owner"
            ],
            "title": "The newPet schema",
            "type": "object",
            "properties": {
                "name": {
                    "$id": "#/properties/newPet/properties/name",
                    "pattern": "^[A-Za-z ]*$",
                    "type": "string",
                    "title": "The name schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "name"
                    ]
                },
                "date_of_birth": {
                    "$id": "#/properties/newPet/properties/date_of_birth",
                    "type": "string",
                    "pattern": "^[1-9][0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])",
                    "title": "The date_of_birth schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "2019-08-20"
                    ]
                },
                "sex": {
                    "$id": "#/properties/newPet/properties/sex",
                    "type": "string",
                    "title": "The sex schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "Samica"
                    ],
                    "enum": ["Samiec", "Samica"]
                },
                "species": {
                    "$id": "#/properties/newPet/properties/species",
                    "type": "string",
                    "pattern": "^[A-Za-z ]*$",
                    "title": "The species schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "pies"
                    ]
                },
                "additional_information": {
                    "$id": "#/properties/newPet/properties/additional_information",
                    "type": "string",
                    "title": "The additional_information schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "albinos"
                    ]
                },
                "owner": {
                    "$id": "#/properties/newPet/properties/owner",
                    "type": "integer",
                    "title": "The owner schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": 0,
                    "examples": [
                        1
                    ]
                },
                "newOwner": {
                    "$id": "#/properties/newPet/properties/newOwner",
                    "type": "object",
                    "title": "The newOwner schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": {},
                    "examples": [
                        {
                            "first_name": "first_name",
                            "last_name": "last_name",
                            "email": "email",
                            "phone_number": "phone_number"
                        }
                    ],
                    "required": [
                        "first_name",
                        "last_name",
                        "email",
                        "phone_number"
                    ],
                    "properties": {
                        "first_name": {
                            "$id": "#/properties/newPet/properties/newOwner/properties/first_name",
                            "type": "string",
                            "title": "The first_name schema",
                            "pattern": "^[A-ZÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð][a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]+$",
                            "description": "An explanation about the purpose of this instance.",
                            "default": "",
                            "examples": [
                                "first_name"
                            ]
                        },
                        "last_name": {
                            "$id": "#/properties/newPet/properties/newOwner/properties/last_name",
                            "type": "string",
                            "title": "The last_name schema",
                            "pattern": "^[A-ZÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð][a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]+$",
                            "description": "An explanation about the purpose of this instance.",
                            "default": "",
                            "examples": [
                                "last_name"
                            ]
                        },
                        "email": {
                            "$id": "#/properties/newPet/properties/newOwner/properties/email",
                            "type": "string",
                            "title": "The email schema",
                            "pattern": "^[a-z_.0-9]*@[a-z0-9-]*.[a-z]*$",
                            "description": "An explanation about the purpose of this instance.",
                            "default": "",
                            "examples": [
                                "joannaslyszewska1502@gmail.com"
                            ]
                        },
                        "phone_number": {
                            "$id": "#/properties/newPet/properties/newOwner/properties/phone_number",
                            "type": "string",
                            "title": "The phone_number schema",
                            "pattern": "^([+]?[ 0-9])?(([0-9]{3}|[(]?[0-9]+[)])?([-]?[ ]?[0-9])+){9,15}$",
                            "description": "An explanation about the purpose of this instance.",
                            "default": "",
                            "examples": [
                                "666 666 666"
                            ]
                        }
                    },
                    "additionalProperties": true
                }
            },
            "additionalProperties": true
        },
        "cures": {
            "$id": "#/properties/cures",
            "type": "array",
            "title": "The cures schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                [
                    {
                        "cure": 1,
                        "quantity": 4,
                        "quantity_type": "op"
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/cures/items",
                "anyOf": [
                    {
                        "$id": "#/properties/cures/items/anyOf/0",
                        "type": "object",
                        "title": "The first anyOf schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": {},
                        "examples": [
                            {
                                "cure": 1,
                                "quantity": 4,
                                "quantity_type": "op"
                            }
                        ],
                        "required": [
                            "cure",
                            "quantity",
                            "quantity_type"
                        ],
                        "properties": {
                            "cure": {
                                "$id": "#/properties/cures/items/anyOf/0/properties/cure",
                                "type": "integer",
                                "title": "The cure schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": 0,
                                "examples": [
                                    1
                                ]
                            },
                            "quantity": {
                                "$id": "#/properties/cures/items/anyOf/0/properties/quantity",
                                "type": "integer",
                                "title": "The quantity schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": 0,
                                "examples": [
                                    4
                                ]
                            },
                            "quantity_type": {
                                "$id": "#/properties/cures/items/anyOf/0/properties/quantity_type",
                                "type": "string",
                                "title": "The quantity_type schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": "",
                                "examples": [
                                    "op"
                                ],
                                "enum": ["op", "sz.","lst","ml"]
                            }
                        },
                        "additionalProperties": true
                    }
                ]
            }
        }
    },
    "additionalProperties": true
}

=== Lavie-Inzynierka/klinikaWeterynaryjna/static/json/addprescription.json
{
  "code": "9651742898673848748872",
  "expiration_date": "2022-03-10",
  "pet": 0,
  "newPet": {
    "name": "Belle",
    "date_of_birth": "2019-08-20",
    "sex": "Samica",
    "species": "pies",
    "additional_information": "Labrador retriever biszkoptowa sierść",
    "owner": 0,
    "newOwner": {
      "first_name": "Joanna",
      "last_name": "Slyszewska",
      "email": "joannaslyszewska1502@gmail.com",
      "phone_number": "+48 666 666 666"
    }
  },
  "cures": [
    {
      "cure": 2,
      "quantity": 10,
      "quantity_type": "sz."
    }
  ]
}
